package flow2_team;

/**
 * Flow 2 - "Team"
 * Udarbejdet af:
 * Andreas og Laura
 * Torsdag 10.10.2013
 */

import java.awt.Panel;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.text.NavigationFilter;

public class GUI extends javax.swing.JFrame
{
    //Herunder ses attributterne:
    DefaultListModel personerUdenforTeams;
    DefaultListModel team1Listen;
    DefaultListModel team2Listen;
    DefaultListModel team3Listen;
    DefaultListModel team4Listen;
    DefaultListModel allePersonerIAllePersoner;
    
    //Herunder instantieres Control-klassen:
    Control control = new Control();

    //Herunder ses konstruktøren "GUI":
    public GUI()
    {
        initComponents();

        //Herunder instantieres DefaultListModel, og jList's sættes til, at parre informationer med attributterne.
        personerUdenforTeams = new DefaultListModel();
        team1Listen = new DefaultListModel();
        team2Listen = new DefaultListModel();
        team3Listen = new DefaultListModel();
        team4Listen = new DefaultListModel();
        allePersonerIAllePersoner = new DefaultListModel();

        jList2_AllePersonerUdenforTeams.setModel(personerUdenforTeams);
        jList2_TeamNo1.setModel(team1Listen);
        jList2_TeamNo2.setModel(team2Listen);
        jList2_TeamNo3.setModel(team3Listen);
        jList2_TeamNo4.setModel(team4Listen);
        jList1_AllePersonerIAllePersoner.setModel(allePersonerIAllePersoner);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1_Forside = new javax.swing.JPanel();
        jButton1_OpretTeam = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1_OpretPerson = new javax.swing.JButton();
        jPanel2_OpretPerson = new javax.swing.JPanel();
        jLabel2_Navn = new javax.swing.JLabel();
        jTextField1_Fornavn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1_AdministratorPoint = new javax.swing.JTextField();
        jTextField2_CreativePoint = new javax.swing.JTextField();
        jTextField3_AnalystPoint = new javax.swing.JTextField();
        jTextField4_FinisherPoint = new javax.swing.JTextField();
        jButton1_OK_OpretPerson = new javax.swing.JButton();
        jButton1_GåTilForsiden_FraOpretPerson = new javax.swing.JButton();
        jPanel3_AllePersoner = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1_AllePersonerIAllePersoner = new javax.swing.JList();
        jButton1_GåTilForsiden_FraAllePersoner = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8_Navn = new javax.swing.JLabel();
        jLabel11_Team = new javax.swing.JLabel();
        jLabel8_Navnet = new javax.swing.JLabel();
        jLabel11_Teamet = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13_AdministratorPoint = new javax.swing.JLabel();
        jLabel14_AnalystPoint = new javax.swing.JLabel();
        jLabel15_CreativePoint = new javax.swing.JLabel();
        jLabel16_FinisherPoint = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton1_SletPerson = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel4_OpretTeam = new javax.swing.JPanel();
        jButton3_GåTilForsiden_FraOpretTeam = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jList2_AllePersonerUdenforTeams = new javax.swing.JList();
        jButton1_Tilføj = new javax.swing.JButton();
        jButton2_Fjern = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1__TeamNo1 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jList2_TeamNo1 = new javax.swing.JList();
        jPanel2_TeamNo2 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jList2_TeamNo2 = new javax.swing.JList();
        jPanel3_TeamNo3 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jList2_TeamNo3 = new javax.swing.JList();
        jPanel4_TeamNo4 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jList2_TeamNo4 = new javax.swing.JList();
        jButton1_HentAllePersoner = new javax.swing.JButton();
        jPanel5_AlleTeams = new javax.swing.JPanel();
        jButton1_Team1 = new javax.swing.JButton();
        jButton2_Team2 = new javax.swing.JButton();
        jButton3_Team3 = new javax.swing.JButton();
        jButton4_Team4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2_Team1 = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3_Team2 = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList4_Team3 = new javax.swing.JList();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList5_Team4 = new javax.swing.JList();
        jButton5_GåTilForsiden_FraAlleTeams = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1_OpretTeam.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        jButton1_OpretTeam.setText("OPRET TEAM");
        jButton1_OpretTeam.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1_OpretTeamActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 30)); // NOI18N
        jLabel1.setText("TEAM APPLIKATION");

        jButton1_OpretPerson.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        jButton1_OpretPerson.setText("OPRET PERSON");
        jButton1_OpretPerson.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1_OpretPersonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1_ForsideLayout = new org.jdesktop.layout.GroupLayout(jPanel1_Forside);
        jPanel1_Forside.setLayout(jPanel1_ForsideLayout);
        jPanel1_ForsideLayout.setHorizontalGroup(
            jPanel1_ForsideLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1_ForsideLayout.createSequentialGroup()
                .add(85, 85, 85)
                .add(jButton1_OpretTeam, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 164, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 203, Short.MAX_VALUE)
                .add(jButton1_OpretPerson, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 172, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(73, 73, 73))
            .add(jPanel1_ForsideLayout.createSequentialGroup()
                .add(180, 180, 180)
                .add(jLabel1)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1_ForsideLayout.setVerticalGroup(
            jPanel1_ForsideLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1_ForsideLayout.createSequentialGroup()
                .add(18, 18, 18)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 47, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jPanel1_ForsideLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton1_OpretPerson, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton1_OpretTeam, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 66, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(286, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("FORSIDE", jPanel1_Forside);

        jLabel2_Navn.setText("Navn:");

        jTextField1_Fornavn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextField1_FornavnActionPerformed(evt);
            }
        });

        jLabel2.setText("Fordel 30 point mellem de 4 forskellige roller:");

        jLabel3.setText("ADMINISTRATOR");

        jLabel4.setText("ANALYST");

        jLabel5.setText("CREATIVE");

        jLabel6.setText("FINISHER");

        jTextField1_AdministratorPoint.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextField1_AdministratorPointActionPerformed(evt);
            }
        });

        jButton1_OK_OpretPerson.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        jButton1_OK_OpretPerson.setText("OK");
        jButton1_OK_OpretPerson.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1_OK_OpretPersonActionPerformed(evt);
            }
        });

        jButton1_GåTilForsiden_FraOpretPerson.setText("Gå til Forsiden");
        jButton1_GåTilForsiden_FraOpretPerson.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1_GåTilForsiden_FraOpretPersonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2_OpretPersonLayout = new org.jdesktop.layout.GroupLayout(jPanel2_OpretPerson);
        jPanel2_OpretPerson.setLayout(jPanel2_OpretPersonLayout);
        jPanel2_OpretPersonLayout.setHorizontalGroup(
            jPanel2_OpretPersonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2_OpretPersonLayout.createSequentialGroup()
                .add(jPanel2_OpretPersonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2_OpretPersonLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(jButton1_GåTilForsiden_FraOpretPerson, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 143, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel2_OpretPersonLayout.createSequentialGroup()
                        .add(21, 21, 21)
                        .add(jPanel2_OpretPersonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel2_OpretPersonLayout.createSequentialGroup()
                                .add(jLabel2_Navn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 64, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jTextField1_Fornavn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 168, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 309, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPanel2_OpretPersonLayout.createSequentialGroup()
                                .add(jPanel2_OpretPersonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 112, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 64, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 66, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jButton1_OK_OpretPerson)
                                    .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 66, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel2_OpretPersonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jTextField3_AnalystPoint)
                                    .add(jTextField1_AdministratorPoint, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                                    .add(jTextField2_CreativePoint)
                                    .add(jTextField4_FinisherPoint))))))
                .add(110, 367, Short.MAX_VALUE))
        );
        jPanel2_OpretPersonLayout.setVerticalGroup(
            jPanel2_OpretPersonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2_OpretPersonLayout.createSequentialGroup()
                .add(34, 34, 34)
                .add(jPanel2_OpretPersonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jLabel2_Navn, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jTextField1_Fornavn))
                .add(52, 52, 52)
                .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jPanel2_OpretPersonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jTextField1_AdministratorPoint, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2_OpretPersonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(jTextField3_AnalystPoint, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2_OpretPersonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jTextField2_CreativePoint, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .add(jLabel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2_OpretPersonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(jTextField4_FinisherPoint, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(38, 38, 38)
                .add(jButton1_OK_OpretPerson)
                .add(46, 46, 46)
                .add(jButton1_GåTilForsiden_FraOpretPerson)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Opret Person", jPanel2_OpretPerson);

        jScrollPane1.setViewportView(jList1_AllePersonerIAllePersoner);

        jButton1_GåTilForsiden_FraAllePersoner.setText("Gå til Forsiden");
        jButton1_GåTilForsiden_FraAllePersoner.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1_GåTilForsiden_FraAllePersonerActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        jLabel7.setText("PERSON INFO");

        jLabel8_Navn.setText("NAVN: ");

        jLabel11_Team.setText("TEAM: ");

        jLabel8_Navnet.setText("Fornavn(e)");

        jLabel11_Teamet.setText("Teamets Navn");

        jLabel8.setText("POINT-FORDELING:");

        jLabel9.setText("Administrator: ");

        jLabel10.setText("Analyst: ");

        jLabel11.setText("Creative: ");

        jLabel12.setText("Finisher: ");

        jLabel13_AdministratorPoint.setText("0-30");

        jLabel14_AnalystPoint.setText("0-30");

        jLabel15_CreativePoint.setText("0-30");

        jLabel16_FinisherPoint.setText("0-30");

        jLabel17.setText("point");

        jLabel18.setText("point");

        jLabel19.setText("point");

        jLabel20.setText("point");

        jButton1_SletPerson.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        jButton1_SletPerson.setText("SLET PERSON");

        jButton1.setText("Hent Personer ");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel3_AllePersonerLayout = new org.jdesktop.layout.GroupLayout(jPanel3_AllePersoner);
        jPanel3_AllePersoner.setLayout(jPanel3_AllePersonerLayout);
        jPanel3_AllePersonerLayout.setHorizontalGroup(
            jPanel3_AllePersonerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3_AllePersonerLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3_AllePersonerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 318, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel3_AllePersonerLayout.createSequentialGroup()
                        .add(jButton1_GåTilForsiden_FraAllePersoner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 143, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 137, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(jPanel3_AllePersonerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3_AllePersonerLayout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(jPanel3_AllePersonerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel3_AllePersonerLayout.createSequentialGroup()
                                .add(0, 135, Short.MAX_VALUE)
                                .add(jLabel7)
                                .add(104, 104, 104))
                            .add(jPanel3_AllePersonerLayout.createSequentialGroup()
                                .add(jPanel3_AllePersonerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jPanel3_AllePersonerLayout.createSequentialGroup()
                                        .add(jPanel3_AllePersonerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jLabel8_Navn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(jLabel11_Team))
                                        .add(18, 18, 18)
                                        .add(jPanel3_AllePersonerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                            .add(jLabel8_Navnet, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                                            .add(jLabel11_Teamet, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .add(jPanel3_AllePersonerLayout.createSequentialGroup()
                                        .add(jPanel3_AllePersonerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jLabel9)
                                            .add(jLabel10)
                                            .add(jLabel11)
                                            .add(jLabel12))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jPanel3_AllePersonerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                            .add(jLabel13_AdministratorPoint, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                            .add(jLabel14_AnalystPoint, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .add(jLabel15_CreativePoint, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .add(jLabel16_FinisherPoint, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jPanel3_AllePersonerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                            .add(jLabel17, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                            .add(jLabel18, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .add(jLabel19, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .add(jLabel20, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .add(jLabel8))
                                .addContainerGap(26, Short.MAX_VALUE))))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3_AllePersonerLayout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jButton1_SletPerson)
                        .addContainerGap())))
        );
        jPanel3_AllePersonerLayout.setVerticalGroup(
            jPanel3_AllePersonerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3_AllePersonerLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3_AllePersonerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3_AllePersonerLayout.createSequentialGroup()
                        .add(jLabel7)
                        .add(10, 10, 10)
                        .add(jPanel3_AllePersonerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel8_Navn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel8_Navnet))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel3_AllePersonerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel11_Team, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel11_Teamet))
                        .add(49, 49, 49)
                        .add(jLabel8)
                        .add(18, 18, 18)
                        .add(jPanel3_AllePersonerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel9)
                            .add(jLabel13_AdministratorPoint)
                            .add(jLabel17))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel3_AllePersonerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel10)
                            .add(jLabel14_AnalystPoint)
                            .add(jLabel18))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel3_AllePersonerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel11)
                            .add(jLabel15_CreativePoint)
                            .add(jLabel19))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel3_AllePersonerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel12)
                            .add(jLabel16_FinisherPoint)
                            .add(jLabel20))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 93, Short.MAX_VALUE)
                        .add(jButton1_SletPerson))
                    .add(jScrollPane1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3_AllePersonerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton1_GåTilForsiden_FraAllePersoner)
                    .add(jButton1))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Alle Personer", jPanel3_AllePersoner);

        jButton3_GåTilForsiden_FraOpretTeam.setText("Gå til Forsiden");
        jButton3_GåTilForsiden_FraOpretTeam.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton3_GåTilForsiden_FraOpretTeamActionPerformed(evt);
            }
        });

        jScrollPane6.setViewportView(jList2_AllePersonerUdenforTeams);

        jButton1_Tilføj.setText("Tilføj >>");
        jButton1_Tilføj.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1_TilføjActionPerformed(evt);
            }
        });

        jButton2_Fjern.setText("<< Fjern");
        jButton2_Fjern.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2_FjernActionPerformed(evt);
            }
        });

        jScrollPane8.setViewportView(jList2_TeamNo1);

        org.jdesktop.layout.GroupLayout jPanel1__TeamNo1Layout = new org.jdesktop.layout.GroupLayout(jPanel1__TeamNo1);
        jPanel1__TeamNo1.setLayout(jPanel1__TeamNo1Layout);
        jPanel1__TeamNo1Layout.setHorizontalGroup(
            jPanel1__TeamNo1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1__TeamNo1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1__TeamNo1Layout.setVerticalGroup(
            jPanel1__TeamNo1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1__TeamNo1Layout.createSequentialGroup()
                .add(jScrollPane8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Team1", jPanel1__TeamNo1);

        jList2_TeamNo2.setModel(new javax.swing.AbstractListModel()
        {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane7.setViewportView(jList2_TeamNo2);

        org.jdesktop.layout.GroupLayout jPanel2_TeamNo2Layout = new org.jdesktop.layout.GroupLayout(jPanel2_TeamNo2);
        jPanel2_TeamNo2.setLayout(jPanel2_TeamNo2Layout);
        jPanel2_TeamNo2Layout.setHorizontalGroup(
            jPanel2_TeamNo2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2_TeamNo2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2_TeamNo2Layout.setVerticalGroup(
            jPanel2_TeamNo2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2_TeamNo2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Team2", jPanel2_TeamNo2);

        jScrollPane9.setViewportView(jList2_TeamNo3);

        org.jdesktop.layout.GroupLayout jPanel3_TeamNo3Layout = new org.jdesktop.layout.GroupLayout(jPanel3_TeamNo3);
        jPanel3_TeamNo3.setLayout(jPanel3_TeamNo3Layout);
        jPanel3_TeamNo3Layout.setHorizontalGroup(
            jPanel3_TeamNo3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3_TeamNo3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane9, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3_TeamNo3Layout.setVerticalGroup(
            jPanel3_TeamNo3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3_TeamNo3Layout.createSequentialGroup()
                .add(jScrollPane9, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Team3", jPanel3_TeamNo3);

        jScrollPane10.setViewportView(jList2_TeamNo4);

        org.jdesktop.layout.GroupLayout jPanel4_TeamNo4Layout = new org.jdesktop.layout.GroupLayout(jPanel4_TeamNo4);
        jPanel4_TeamNo4.setLayout(jPanel4_TeamNo4Layout);
        jPanel4_TeamNo4Layout.setHorizontalGroup(
            jPanel4_TeamNo4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4_TeamNo4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane10, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4_TeamNo4Layout.setVerticalGroup(
            jPanel4_TeamNo4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4_TeamNo4Layout.createSequentialGroup()
                .add(jScrollPane10, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Team4", jPanel4_TeamNo4);

        jButton1_HentAllePersoner.setText("HENT ALLE PERSONER");
        jButton1_HentAllePersoner.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1_HentAllePersonerActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel4_OpretTeamLayout = new org.jdesktop.layout.GroupLayout(jPanel4_OpretTeam);
        jPanel4_OpretTeam.setLayout(jPanel4_OpretTeamLayout);
        jPanel4_OpretTeamLayout.setHorizontalGroup(
            jPanel4_OpretTeamLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4_OpretTeamLayout.createSequentialGroup()
                .add(jPanel4_OpretTeamLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel4_OpretTeamLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(jButton3_GåTilForsiden_FraOpretTeam, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 143, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel4_OpretTeamLayout.createSequentialGroup()
                        .add(jPanel4_OpretTeamLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel4_OpretTeamLayout.createSequentialGroup()
                                .add(21, 21, 21)
                                .add(jScrollPane6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 209, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jPanel4_OpretTeamLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jButton1_Tilføj)
                                    .add(jButton2_Fjern)))
                            .add(jPanel4_OpretTeamLayout.createSequentialGroup()
                                .add(30, 30, 30)
                                .add(jButton1_HentAllePersoner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 191, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jTabbedPane2)))
                .addContainerGap())
        );
        jPanel4_OpretTeamLayout.setVerticalGroup(
            jPanel4_OpretTeamLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4_OpretTeamLayout.createSequentialGroup()
                .add(jPanel4_OpretTeamLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel4_OpretTeamLayout.createSequentialGroup()
                        .add(114, 114, 114)
                        .add(jButton1_Tilføj)
                        .add(18, 18, 18)
                        .add(jButton2_Fjern)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jButton3_GåTilForsiden_FraOpretTeam))
                    .add(jPanel4_OpretTeamLayout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(jPanel4_OpretTeamLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jTabbedPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 334, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPanel4_OpretTeamLayout.createSequentialGroup()
                                .add(jButton1_HentAllePersoner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jScrollPane6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 282, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(0, 77, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Opret Team", jPanel4_OpretTeam);

        jButton1_Team1.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 36)); // NOI18N
        jButton1_Team1.setText("TEAM 1");

        jButton2_Team2.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 36)); // NOI18N
        jButton2_Team2.setText("TEAM 2");

        jButton3_Team3.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 36)); // NOI18N
        jButton3_Team3.setText("TEAM 3");

        jButton4_Team4.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 36)); // NOI18N
        jButton4_Team4.setText("TEAM 4");

        jList2_Team1.setModel(new javax.swing.AbstractListModel()
        {
            String[] strings = { "Administrator: ", "Analyst: ", "Creative: ", "Finisher: " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2_Team1);

        jList3_Team2.setModel(new javax.swing.AbstractListModel()
        {
            String[] strings = { "Administrator: ", "Analyst: ", "Creative: ", "Finisher: " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList3_Team2);

        jList4_Team3.setModel(new javax.swing.AbstractListModel()
        {
            String[] strings = { "Administrator: ", "Analyst: ", "Creative: ", "Finisher: " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList4_Team3);

        jList5_Team4.setModel(new javax.swing.AbstractListModel()
        {
            String[] strings = { "Administrator: ", "Analyst: ", "Creative: ", "Finisher: " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(jList5_Team4);

        jButton5_GåTilForsiden_FraAlleTeams.setText("Gå til Forsiden");
        jButton5_GåTilForsiden_FraAlleTeams.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton5_GåTilForsiden_FraAlleTeamsActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel5_AlleTeamsLayout = new org.jdesktop.layout.GroupLayout(jPanel5_AlleTeams);
        jPanel5_AlleTeams.setLayout(jPanel5_AlleTeamsLayout);
        jPanel5_AlleTeamsLayout.setHorizontalGroup(
            jPanel5_AlleTeamsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5_AlleTeamsLayout.createSequentialGroup()
                .add(34, 34, 34)
                .add(jPanel5_AlleTeamsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel5_AlleTeamsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                        .add(jScrollPane4))
                    .add(jButton3_Team3)
                    .add(jButton1_Team1))
                .add(49, 49, 49)
                .add(jPanel5_AlleTeamsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel5_AlleTeamsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(jScrollPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                        .add(jScrollPane5))
                    .add(jButton2_Team2)
                    .add(jButton4_Team4))
                .addContainerGap(94, Short.MAX_VALUE))
            .add(jPanel5_AlleTeamsLayout.createSequentialGroup()
                .addContainerGap()
                .add(jButton5_GåTilForsiden_FraAlleTeams, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 143, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );
        jPanel5_AlleTeamsLayout.setVerticalGroup(
            jPanel5_AlleTeamsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5_AlleTeamsLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel5_AlleTeamsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jButton1_Team1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton2_Team2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel5_AlleTeamsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jScrollPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel5_AlleTeamsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jButton3_Team3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton4_Team4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel5_AlleTeamsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .add(jScrollPane4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .add(18, 18, 18)
                .add(jButton5_GåTilForsiden_FraAlleTeams)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Alle Teams", jPanel5_AlleTeams);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_OpretTeamActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1_OpretTeamActionPerformed
    {//GEN-HEADEREND:event_jButton1_OpretTeamActionPerformed
        //Når der trykkes på "Opret Team"-knappen, skal vi skifte til panelet "Opret Team".
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_jButton1_OpretTeamActionPerformed

    private void jButton1_GåTilForsiden_FraOpretPersonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1_GåTilForsiden_FraOpretPersonActionPerformed
    {//GEN-HEADEREND:event_jButton1_GåTilForsiden_FraOpretPersonActionPerformed
        //Når der trykkes på "Gå til Forsiden", skal vi skifte til Panel 1 (Forsiden).
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1_GåTilForsiden_FraOpretPersonActionPerformed

    private void jButton1_OpretPersonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1_OpretPersonActionPerformed
    {//GEN-HEADEREND:event_jButton1_OpretPersonActionPerformed
        //Når der trykkes på "Opret Person"-knappen, skal vi skifte til panelet "Opret Person".
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jButton1_OpretPersonActionPerformed

    private void jButton1_GåTilForsiden_FraAllePersonerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1_GåTilForsiden_FraAllePersonerActionPerformed
    {//GEN-HEADEREND:event_jButton1_GåTilForsiden_FraAllePersonerActionPerformed
        //Når der trykkes på "Gå til Forsiden", skal vi skifte til Panel 1 (Forsiden).
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1_GåTilForsiden_FraAllePersonerActionPerformed

    private void jButton3_GåTilForsiden_FraOpretTeamActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3_GåTilForsiden_FraOpretTeamActionPerformed
    {//GEN-HEADEREND:event_jButton3_GåTilForsiden_FraOpretTeamActionPerformed
        //Når der trykkes på "Gå til Forsiden", skal vi skifte til Panel 1 (Forsiden).
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton3_GåTilForsiden_FraOpretTeamActionPerformed

    private void jButton5_GåTilForsiden_FraAlleTeamsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton5_GåTilForsiden_FraAlleTeamsActionPerformed
    {//GEN-HEADEREND:event_jButton5_GåTilForsiden_FraAlleTeamsActionPerformed
        //Når der trykkes på "Gå til Forsiden", skal vi skifte til Panel 1 (Forsiden).
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton5_GåTilForsiden_FraAlleTeamsActionPerformed

    private void jButton1_TilføjActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1_TilføjActionPerformed
    {//GEN-HEADEREND:event_jButton1_TilføjActionPerformed
        //Hvis der trykkes på "Tilføj", bliver en person flyttet fra liste 1 (Personer udenfor teams) til en valgt team-liste:
        if (jTabbedPane2.getSelectedIndex() == 0)
        {
            Object valgt1 = jList2_AllePersonerUdenforTeams.getSelectedValue();
            
            if (team1Listen.size() < 4)
            {
                personerUdenforTeams.removeElement(valgt1);
                team1Listen.addElement(valgt1);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Der må max være 4 personer på et team!");
            }
        }

        if (jTabbedPane2.getSelectedIndex() == 1)
        {
            Object valgt2 = jList2_AllePersonerUdenforTeams.getSelectedValue();
            
            if (team2Listen.size() < 4)
            {
                personerUdenforTeams.removeElement(valgt2);
                team2Listen.addElement(valgt2);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Der må max være 4 personer på et team!");
            }
        }

        if (jTabbedPane2.getSelectedIndex() == 2)
        {
            Object valgt3 = jList2_AllePersonerUdenforTeams.getSelectedValue();
            
            if (team3Listen.size() < 4)
            {
                personerUdenforTeams.removeElement(valgt3);
                team3Listen.addElement(valgt3);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Der må max være 4 personer på et team!");
            }
        }

        if (jTabbedPane2.getSelectedIndex() == 3)
        {
            Object valgt4 = jList2_AllePersonerUdenforTeams.getSelectedValue();

            if (team4Listen.size() < 4)
            {
                personerUdenforTeams.removeElement(valgt4);
                team4Listen.addElement(valgt4);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Der må max være 4 personer på et team!");
            }
        }
    }//GEN-LAST:event_jButton1_TilføjActionPerformed

    private void jButton2_FjernActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2_FjernActionPerformed
    {//GEN-HEADEREND:event_jButton2_FjernActionPerformed
        //Hvis der trykkes på "Fjern", bliver en person flyttet fra team-listen og tilbage til liste 1 (Personer udenfor teams):
        if (jTabbedPane2.getSelectedIndex() == 0)
        {
            Object valgt1 = jList2_TeamNo1.getSelectedValue();
            team1Listen.removeElement(valgt1);
            personerUdenforTeams.addElement(valgt1);
        }

        if (jTabbedPane2.getSelectedIndex() == 1)
        {
            Object valgt2 = jList2_TeamNo2.getSelectedValue();
            team2Listen.removeElement(valgt2);
            personerUdenforTeams.addElement(valgt2);
        }

        if (jTabbedPane2.getSelectedIndex() == 2)
        {
            Object valgt3 = jList2_TeamNo3.getSelectedValue();
            team3Listen.removeElement(valgt3);
            personerUdenforTeams.addElement(valgt3);
        }

        if (jTabbedPane2.getSelectedIndex() == 3)
        {
            Object valgt4 = jList2_TeamNo4.getSelectedValue();
            team4Listen.removeElement(valgt4);
            personerUdenforTeams.addElement(valgt4);
        }
    }//GEN-LAST:event_jButton2_FjernActionPerformed

    private void jButton1_HentAllePersonerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1_HentAllePersonerActionPerformed
    {//GEN-HEADEREND:event_jButton1_HentAllePersonerActionPerformed
        //
        ArrayList<Persons> resultat = control.getPeople();
        for (int i = 0; i < resultat.size(); i++)
        {
            personerUdenforTeams.addElement(resultat.get(i).toString());
        }
    }//GEN-LAST:event_jButton1_HentAllePersonerActionPerformed

    private void jTextField1_FornavnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_FornavnActionPerformed
        //
    }//GEN-LAST:event_jTextField1_FornavnActionPerformed

    private void jButton1_OK_OpretPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_OK_OpretPersonActionPerformed
        //
        String navn = jTextField1_Fornavn.getText();
        int administratorPoint = Integer.parseInt(jTextField1_AdministratorPoint.getText());
        int creativePoint = Integer.parseInt(jTextField2_CreativePoint.getText());
        int analystPoint = Integer.parseInt(jTextField3_AnalystPoint.getText());
        int finisherPoint = Integer.parseInt(jTextField4_FinisherPoint.getText());

        if ((administratorPoint + creativePoint + analystPoint + finisherPoint) != 30)
        {
            JOptionPane.showMessageDialog(this, "Du skal fordele 30 point i alt!");
        }

        control.addPerson(navn, administratorPoint, creativePoint, analystPoint, finisherPoint);
        control.saveToFile();
    }//GEN-LAST:event_jButton1_OK_OpretPersonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //
        ArrayList<Persons> resultat = control.getPeople();

        for (int i = 0; i < resultat.size(); i++)
        {
            allePersonerIAllePersoner.addElement(resultat.get(i).toString());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1_AdministratorPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_AdministratorPointActionPerformed
        //
    }//GEN-LAST:event_jTextField1_AdministratorPointActionPerformed

    //Herunder ses main-metoden:
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new GUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1_GåTilForsiden_FraAllePersoner;
    private javax.swing.JButton jButton1_GåTilForsiden_FraOpretPerson;
    private javax.swing.JButton jButton1_HentAllePersoner;
    private javax.swing.JButton jButton1_OK_OpretPerson;
    private javax.swing.JButton jButton1_OpretPerson;
    private javax.swing.JButton jButton1_OpretTeam;
    private javax.swing.JButton jButton1_SletPerson;
    private javax.swing.JButton jButton1_Team1;
    private javax.swing.JButton jButton1_Tilføj;
    private javax.swing.JButton jButton2_Fjern;
    private javax.swing.JButton jButton2_Team2;
    private javax.swing.JButton jButton3_GåTilForsiden_FraOpretTeam;
    private javax.swing.JButton jButton3_Team3;
    private javax.swing.JButton jButton4_Team4;
    private javax.swing.JButton jButton5_GåTilForsiden_FraAlleTeams;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel11_Team;
    private javax.swing.JLabel jLabel11_Teamet;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13_AdministratorPoint;
    private javax.swing.JLabel jLabel14_AnalystPoint;
    private javax.swing.JLabel jLabel15_CreativePoint;
    private javax.swing.JLabel jLabel16_FinisherPoint;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel2_Navn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel8_Navn;
    private javax.swing.JLabel jLabel8_Navnet;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1_AllePersonerIAllePersoner;
    private javax.swing.JList jList2_AllePersonerUdenforTeams;
    private javax.swing.JList jList2_Team1;
    private javax.swing.JList jList2_TeamNo1;
    private javax.swing.JList jList2_TeamNo2;
    private javax.swing.JList jList2_TeamNo3;
    private javax.swing.JList jList2_TeamNo4;
    private javax.swing.JList jList3_Team2;
    private javax.swing.JList jList4_Team3;
    private javax.swing.JList jList5_Team4;
    private javax.swing.JPanel jPanel1_Forside;
    private javax.swing.JPanel jPanel1__TeamNo1;
    private javax.swing.JPanel jPanel2_OpretPerson;
    private javax.swing.JPanel jPanel2_TeamNo2;
    private javax.swing.JPanel jPanel3_AllePersoner;
    private javax.swing.JPanel jPanel3_TeamNo3;
    private javax.swing.JPanel jPanel4_OpretTeam;
    private javax.swing.JPanel jPanel4_TeamNo4;
    private javax.swing.JPanel jPanel5_AlleTeams;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField1_AdministratorPoint;
    private javax.swing.JTextField jTextField1_Fornavn;
    private javax.swing.JTextField jTextField2_CreativePoint;
    private javax.swing.JTextField jTextField3_AnalystPoint;
    private javax.swing.JTextField jTextField4_FinisherPoint;
    // End of variables declaration//GEN-END:variables
}
