package flow2_team;

/**
 * Flow 2 - "Team" Udarbejdet af: Andreas og Laura Torsdag 10.10.2013
 */
import java.awt.BorderLayout;
import java.awt.Panel;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.ListModel;
import javax.swing.text.NavigationFilter;

public class GUI extends javax.swing.JFrame
{
    //Herunder ses attributterne:

    DefaultListModel personerUdenforTeams;
    DefaultListModel nytPanel;
    DefaultListModel alleTeams;
    int n;
    int s;
    //Herunder instantieres Control-klassen:
    Control control = new Control();
    ArrayList<DefaultListModel> modelListe = new ArrayList<>();
    ArrayList<JList> listeListe = new ArrayList<>();

    //Herunder ses konstruktøren "GUI":
    public GUI()
    {
        initComponents();

        //Herunder instantieres DefaultListModel, og jList's sættes til, at parre informationer med attributterne.
        personerUdenforTeams = new DefaultListModel();

        alleTeams = new DefaultListModel();

        jList2_AllePersonerUdenforTeams.setModel(personerUdenforTeams);

        jList1_AlleTeams.setModel(alleTeams);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1_Forside = new javax.swing.JPanel();
        jButton1_OpretTeam = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1_OpretPerson = new javax.swing.JButton();
        jPanel4_OpretTeam = new javax.swing.JPanel();
        jButton3_GåTilForsiden_FraOpretTeam = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jList2_AllePersonerUdenforTeams = new javax.swing.JList();
        jButton1_Tilføj = new javax.swing.JButton();
        jButton2_Fjern = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1__TeamNo1 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jList2_TeamNo1 = new javax.swing.JList();
        jButton1_HentAllePersoner = new javax.swing.JButton();
        jButton2_NytTeam = new javax.swing.JButton();
        jButton2_GemTeam = new javax.swing.JButton();
        jLabel7_TeametErGemt = new javax.swing.JLabel();
        jPanel5_AlleTeams = new javax.swing.JPanel();
        jButton5_GåTilForsiden_FraAlleTeams = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1_AlleTeams = new javax.swing.JList();
        jButton2_HentAlleTeams = new javax.swing.JButton();
        jPanel2_OpretPerson = new javax.swing.JPanel();
        jLabel2_Navn = new javax.swing.JLabel();
        jTextField1_Fornavn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1_AdministratorPoint = new javax.swing.JTextField();
        jTextField2_CreativePoint = new javax.swing.JTextField();
        jTextField3_AnalystPoint = new javax.swing.JTextField();
        jTextField4_FinisherPoint = new javax.swing.JTextField();
        jButton1_OK_OpretPerson = new javax.swing.JButton();
        jButton1_GåTilForsiden_FraOpretPerson = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1_OpretTeam.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        jButton1_OpretTeam.setText("OPRET TEAM");
        jButton1_OpretTeam.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1_OpretTeamActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 30)); // NOI18N
        jLabel1.setText("TEAM APPLIKATION");

        jButton1_OpretPerson.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        jButton1_OpretPerson.setText("OPRET PERSON");
        jButton1_OpretPerson.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1_OpretPersonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1_ForsideLayout = new org.jdesktop.layout.GroupLayout(jPanel1_Forside);
        jPanel1_Forside.setLayout(jPanel1_ForsideLayout);
        jPanel1_ForsideLayout.setHorizontalGroup(
            jPanel1_ForsideLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1_ForsideLayout.createSequentialGroup()
                .add(137, 137, 137)
                .add(jButton1_OpretTeam, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 164, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 172, Short.MAX_VALUE)
                .add(jButton1_OpretPerson, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 172, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(145, 145, 145))
            .add(jPanel1_ForsideLayout.createSequentialGroup()
                .add(235, 235, 235)
                .add(jLabel1)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1_ForsideLayout.setVerticalGroup(
            jPanel1_ForsideLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1_ForsideLayout.createSequentialGroup()
                .add(18, 18, 18)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 47, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jPanel1_ForsideLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton1_OpretPerson, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton1_OpretTeam, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 66, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(456, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("FORSIDE", jPanel1_Forside);

        jButton3_GåTilForsiden_FraOpretTeam.setText("Gå til Forsiden");
        jButton3_GåTilForsiden_FraOpretTeam.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton3_GåTilForsiden_FraOpretTeamActionPerformed(evt);
            }
        });

        jScrollPane6.setViewportView(jList2_AllePersonerUdenforTeams);

        jButton1_Tilføj.setText("Tilføj >>");
        jButton1_Tilføj.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1_TilføjActionPerformed(evt);
            }
        });

        jButton2_Fjern.setText("<< Fjern");
        jButton2_Fjern.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2_FjernActionPerformed(evt);
            }
        });

        jScrollPane8.setViewportView(jList2_TeamNo1);

        org.jdesktop.layout.GroupLayout jPanel1__TeamNo1Layout = new org.jdesktop.layout.GroupLayout(jPanel1__TeamNo1);
        jPanel1__TeamNo1.setLayout(jPanel1__TeamNo1Layout);
        jPanel1__TeamNo1Layout.setHorizontalGroup(
            jPanel1__TeamNo1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1__TeamNo1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1__TeamNo1Layout.setVerticalGroup(
            jPanel1__TeamNo1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1__TeamNo1Layout.createSequentialGroup()
                .add(jScrollPane8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("TEAMS", jPanel1__TeamNo1);

        jButton1_HentAllePersoner.setText("HENT ALLE PERSONER");
        jButton1_HentAllePersoner.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1_HentAllePersonerActionPerformed(evt);
            }
        });

        jButton2_NytTeam.setText("NYT TEAM");
        jButton2_NytTeam.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2_NytTeamActionPerformed(evt);
            }
        });

        jButton2_GemTeam.setText("GEM TEAM");
        jButton2_GemTeam.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2_GemTeamActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel4_OpretTeamLayout = new org.jdesktop.layout.GroupLayout(jPanel4_OpretTeam);
        jPanel4_OpretTeam.setLayout(jPanel4_OpretTeamLayout);
        jPanel4_OpretTeamLayout.setHorizontalGroup(
            jPanel4_OpretTeamLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4_OpretTeamLayout.createSequentialGroup()
                .add(jPanel4_OpretTeamLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel4_OpretTeamLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(jButton3_GåTilForsiden_FraOpretTeam, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 143, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel4_OpretTeamLayout.createSequentialGroup()
                        .add(jPanel4_OpretTeamLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel4_OpretTeamLayout.createSequentialGroup()
                                .add(30, 30, 30)
                                .add(jButton1_HentAllePersoner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 191, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel4_OpretTeamLayout.createSequentialGroup()
                                .add(21, 21, 21)
                                .add(jScrollPane6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 209, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel4_OpretTeamLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(jButton2_NytTeam, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(jButton1_Tilføj, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(jButton2_Fjern, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel4_OpretTeamLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel4_OpretTeamLayout.createSequentialGroup()
                                .add(0, 0, Short.MAX_VALUE)
                                .add(jLabel7_TeametErGemt, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 136, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jButton2_GemTeam, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 121, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(124, 124, 124))
                            .add(jTabbedPane2))))
                .addContainerGap())
        );
        jPanel4_OpretTeamLayout.setVerticalGroup(
            jPanel4_OpretTeamLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4_OpretTeamLayout.createSequentialGroup()
                .add(jPanel4_OpretTeamLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel4_OpretTeamLayout.createSequentialGroup()
                        .add(161, 161, 161)
                        .add(jButton2_Fjern))
                    .add(jPanel4_OpretTeamLayout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(jPanel4_OpretTeamLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jTabbedPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 334, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPanel4_OpretTeamLayout.createSequentialGroup()
                                .add(jButton1_HentAllePersoner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel4_OpretTeamLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(jPanel4_OpretTeamLayout.createSequentialGroup()
                                        .add(jButton2_NytTeam)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .add(jButton1_Tilføj, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(180, 180, 180))
                                    .add(jScrollPane6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 282, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel4_OpretTeamLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jButton2_GemTeam, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jLabel7_TeametErGemt, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel4_OpretTeamLayout.createSequentialGroup()
                        .addContainerGap(422, Short.MAX_VALUE)
                        .add(jButton3_GåTilForsiden_FraOpretTeam)))
                .addContainerGap(154, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Opret Team", jPanel4_OpretTeam);

        jButton5_GåTilForsiden_FraAlleTeams.setText("Gå til Forsiden");
        jButton5_GåTilForsiden_FraAlleTeams.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton5_GåTilForsiden_FraAlleTeamsActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jList1_AlleTeams);

        jButton2_HentAlleTeams.setText("HENT ALLE TEAMS");
        jButton2_HentAlleTeams.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2_HentAlleTeamsActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel5_AlleTeamsLayout = new org.jdesktop.layout.GroupLayout(jPanel5_AlleTeams);
        jPanel5_AlleTeams.setLayout(jPanel5_AlleTeamsLayout);
        jPanel5_AlleTeamsLayout.setHorizontalGroup(
            jPanel5_AlleTeamsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5_AlleTeamsLayout.createSequentialGroup()
                .addContainerGap()
                .add(jButton5_GåTilForsiden_FraAlleTeams, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 143, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel5_AlleTeamsLayout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .add(jPanel5_AlleTeamsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 553, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton2_HentAlleTeams, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 172, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(100, 100, 100))
        );
        jPanel5_AlleTeamsLayout.setVerticalGroup(
            jPanel5_AlleTeamsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5_AlleTeamsLayout.createSequentialGroup()
                .add(14, 14, 14)
                .add(jButton2_HentAlleTeams, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 295, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(72, 72, 72)
                .add(jButton5_GåTilForsiden_FraAlleTeams)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Alle Teams", jPanel5_AlleTeams);

        jLabel2_Navn.setText("Navn:");

        jTextField1_Fornavn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextField1_FornavnActionPerformed(evt);
            }
        });

        jLabel2.setText("Fordel 30 point mellem de 4 forskellige roller:");

        jLabel3.setText("ADMINISTRATOR");

        jLabel4.setText("ANALYST");

        jLabel5.setText("CREATIVE");

        jLabel6.setText("FINISHER");

        jTextField1_AdministratorPoint.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextField1_AdministratorPointActionPerformed(evt);
            }
        });

        jButton1_OK_OpretPerson.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        jButton1_OK_OpretPerson.setText("OK");
        jButton1_OK_OpretPerson.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1_OK_OpretPersonActionPerformed(evt);
            }
        });

        jButton1_GåTilForsiden_FraOpretPerson.setText("Gå til Forsiden");
        jButton1_GåTilForsiden_FraOpretPerson.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1_GåTilForsiden_FraOpretPersonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2_OpretPersonLayout = new org.jdesktop.layout.GroupLayout(jPanel2_OpretPerson);
        jPanel2_OpretPerson.setLayout(jPanel2_OpretPersonLayout);
        jPanel2_OpretPersonLayout.setHorizontalGroup(
            jPanel2_OpretPersonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2_OpretPersonLayout.createSequentialGroup()
                .add(jPanel2_OpretPersonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2_OpretPersonLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(jButton1_GåTilForsiden_FraOpretPerson, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 143, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel2_OpretPersonLayout.createSequentialGroup()
                        .add(21, 21, 21)
                        .add(jPanel2_OpretPersonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel2_OpretPersonLayout.createSequentialGroup()
                                .add(jLabel2_Navn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 64, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jTextField1_Fornavn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 168, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel2_OpretPersonLayout.createSequentialGroup()
                                .add(jPanel2_OpretPersonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 309, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2_OpretPersonLayout.createSequentialGroup()
                                        .add(jPanel2_OpretPersonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 66, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(jPanel2_OpretPersonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                                .add(jPanel2_OpretPersonLayout.createSequentialGroup()
                                                    .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 64, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .add(jTextField2_CreativePoint, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                                .add(jPanel2_OpretPersonLayout.createSequentialGroup()
                                                    .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 117, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                    .add(jTextField1_AdministratorPoint, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                                .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel2_OpretPersonLayout.createSequentialGroup()
                                                    .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 66, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .add(jTextField3_AnalystPoint, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                                .add(jTextField4_FinisherPoint, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                        .add(124, 124, 124)))
                                .add(30, 30, 30)
                                .add(jButton1_OK_OpretPerson)))))
                .addContainerGap(355, Short.MAX_VALUE))
        );
        jPanel2_OpretPersonLayout.setVerticalGroup(
            jPanel2_OpretPersonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2_OpretPersonLayout.createSequentialGroup()
                .add(34, 34, 34)
                .add(jPanel2_OpretPersonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jLabel2_Navn, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jTextField1_Fornavn))
                .add(36, 36, 36)
                .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jPanel2_OpretPersonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jTextField1_AdministratorPoint)
                    .add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(28, 28, 28)
                .add(jPanel2_OpretPersonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(jTextField2_CreativePoint))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 61, Short.MAX_VALUE)
                .add(jPanel2_OpretPersonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jTextField3_AnalystPoint, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(19, 19, 19)
                .add(jPanel2_OpretPersonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextField4_FinisherPoint, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton1_OK_OpretPerson))
                .add(33, 33, 33)
                .add(jButton1_GåTilForsiden_FraOpretPerson)
                .add(183, 183, 183))
        );

        jTabbedPane1.addTab("Opret Person", jPanel2_OpretPerson);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jTabbedPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_OpretTeamActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1_OpretTeamActionPerformed
    {//GEN-HEADEREND:event_jButton1_OpretTeamActionPerformed
        //Når der trykkes på "Opret Team"-knappen, skal vi skifte til panelet "Opret Team".
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_jButton1_OpretTeamActionPerformed

    private void jButton1_GåTilForsiden_FraOpretPersonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1_GåTilForsiden_FraOpretPersonActionPerformed
    {//GEN-HEADEREND:event_jButton1_GåTilForsiden_FraOpretPersonActionPerformed
        //Når der trykkes på "Gå til Forsiden", skal vi skifte til Panel 1 (Forsiden).
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1_GåTilForsiden_FraOpretPersonActionPerformed

    private void jButton1_OpretPersonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1_OpretPersonActionPerformed
    {//GEN-HEADEREND:event_jButton1_OpretPersonActionPerformed
        //Når der trykkes på "Opret Person"-knappen, skal vi skifte til panelet "Opret Person".
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jButton1_OpretPersonActionPerformed

    private void jButton3_GåTilForsiden_FraOpretTeamActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3_GåTilForsiden_FraOpretTeamActionPerformed
    {//GEN-HEADEREND:event_jButton3_GåTilForsiden_FraOpretTeamActionPerformed
        //Når der trykkes på "Gå til Forsiden", skal vi skifte til Panel 1 (Forsiden).
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton3_GåTilForsiden_FraOpretTeamActionPerformed

    private void jButton5_GåTilForsiden_FraAlleTeamsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton5_GåTilForsiden_FraAlleTeamsActionPerformed
    {//GEN-HEADEREND:event_jButton5_GåTilForsiden_FraAlleTeamsActionPerformed
        //Når der trykkes på "Gå til Forsiden", skal vi skifte til Panel 1 (Forsiden).
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton5_GåTilForsiden_FraAlleTeamsActionPerformed

    private void jButton1_TilføjActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1_TilføjActionPerformed
    {//GEN-HEADEREND:event_jButton1_TilføjActionPerformed
        //
        if (modelListe.get(jTabbedPane2.getSelectedIndex() - 1).size() < 4)
        {
            Object valgt1 = jList2_AllePersonerUdenforTeams.getSelectedValue();
            personerUdenforTeams.removeElement(valgt1);
            modelListe.get(jTabbedPane2.getSelectedIndex() - 1).addElement(valgt1);
        } else
        {
            JOptionPane.showMessageDialog(this, "Der må max være 4 personer på et team!");
        }
    }//GEN-LAST:event_jButton1_TilføjActionPerformed

    private void jButton2_FjernActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2_FjernActionPerformed
    {//GEN-HEADEREND:event_jButton2_FjernActionPerformed
        //
        Object valgt2 = listeListe.get(jTabbedPane2.getSelectedIndex() - 1).getSelectedValue();
        modelListe.get(jTabbedPane2.getSelectedIndex() - 1).removeElement(valgt2);
        personerUdenforTeams.addElement(valgt2);
    }//GEN-LAST:event_jButton2_FjernActionPerformed

    private void jButton1_HentAllePersonerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1_HentAllePersonerActionPerformed
    {//GEN-HEADEREND:event_jButton1_HentAllePersonerActionPerformed
        personerUdenforTeams.clear();
        //
        ArrayList<Person> resultat = control.getPeople();

        for (int i = 0; i < resultat.size(); i++)
        {
            personerUdenforTeams.addElement(resultat.get(i).toString());
        }
    }//GEN-LAST:event_jButton1_HentAllePersonerActionPerformed

    private void jTextField1_FornavnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_FornavnActionPerformed
        //
    }//GEN-LAST:event_jTextField1_FornavnActionPerformed

    private void jButton1_OK_OpretPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_OK_OpretPersonActionPerformed
        //
        String navn = jTextField1_Fornavn.getText();
        int administratorPoint = Integer.parseInt(jTextField1_AdministratorPoint.getText());
        int creativePoint = Integer.parseInt(jTextField2_CreativePoint.getText());
        int analystPoint = Integer.parseInt(jTextField3_AnalystPoint.getText());
        int finisherPoint = Integer.parseInt(jTextField4_FinisherPoint.getText());

        if ((administratorPoint + creativePoint + analystPoint + finisherPoint) != 30)
        {
            JOptionPane.showMessageDialog(this, "Du skal fordele 30 point i alt!");
        }

        control.addPerson(navn, administratorPoint, creativePoint, analystPoint, finisherPoint);
        control.saveToFile();
        jTextField1_Fornavn.setText("");
        jTextField1_AdministratorPoint.setText("");
        jTextField2_CreativePoint.setText("");
        jTextField3_AnalystPoint.setText("");
        jTextField4_FinisherPoint.setText("");
    }//GEN-LAST:event_jButton1_OK_OpretPersonActionPerformed

    private void jTextField1_AdministratorPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_AdministratorPointActionPerformed
        //
    }//GEN-LAST:event_jTextField1_AdministratorPointActionPerformed

    private void jButton2_NytTeamActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2_NytTeamActionPerformed
    {//GEN-HEADEREND:event_jButton2_NytTeamActionPerformed
        n = n + 1;
        JPanel nytPanel = new JPanel(new BorderLayout());
        jTabbedPane2.addTab("Team" + n, nytPanel);
        DefaultListModel model = new DefaultListModel();
        JList nyListe = new JList(model);
        nytPanel.add(nyListe);

        modelListe.add(model);
        listeListe.add(nyListe);
        
        jLabel7_TeametErGemt.setText("");
    }//GEN-LAST:event_jButton2_NytTeamActionPerformed

    private void jButton2_GemTeamActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2_GemTeamActionPerformed
    {//GEN-HEADEREND:event_jButton2_GemTeamActionPerformed
        String navn = jTabbedPane2.getTitleAt(jTabbedPane2.getSelectedIndex());
        control.addTeam(navn);
        control.saveTeamToFile();
        
        jLabel7_TeametErGemt.setText("TEAMET ER GEMT...");
    }//GEN-LAST:event_jButton2_GemTeamActionPerformed

    private void jButton2_HentAlleTeamsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2_HentAlleTeamsActionPerformed
    {//GEN-HEADEREND:event_jButton2_HentAlleTeamsActionPerformed
        //
        alleTeams.clear();

        //
        ArrayList<Team> teamresultat = control.getTeam();

        for (int i = 0; i < teamresultat.size(); i++)
        {
            alleTeams.addElement(teamresultat.get(i).toString());
        }
    }//GEN-LAST:event_jButton2_HentAlleTeamsActionPerformed

    //Herunder ses main-metoden:
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new GUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_GåTilForsiden_FraOpretPerson;
    private javax.swing.JButton jButton1_HentAllePersoner;
    private javax.swing.JButton jButton1_OK_OpretPerson;
    private javax.swing.JButton jButton1_OpretPerson;
    private javax.swing.JButton jButton1_OpretTeam;
    private javax.swing.JButton jButton1_Tilføj;
    private javax.swing.JButton jButton2_Fjern;
    private javax.swing.JButton jButton2_GemTeam;
    private javax.swing.JButton jButton2_HentAlleTeams;
    private javax.swing.JButton jButton2_NytTeam;
    private javax.swing.JButton jButton3_GåTilForsiden_FraOpretTeam;
    private javax.swing.JButton jButton5_GåTilForsiden_FraAlleTeams;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel2_Navn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7_TeametErGemt;
    private javax.swing.JList jList1_AlleTeams;
    private javax.swing.JList jList2_AllePersonerUdenforTeams;
    private javax.swing.JList jList2_TeamNo1;
    private javax.swing.JPanel jPanel1_Forside;
    private javax.swing.JPanel jPanel1__TeamNo1;
    private javax.swing.JPanel jPanel2_OpretPerson;
    private javax.swing.JPanel jPanel4_OpretTeam;
    private javax.swing.JPanel jPanel5_AlleTeams;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField1_AdministratorPoint;
    private javax.swing.JTextField jTextField1_Fornavn;
    private javax.swing.JTextField jTextField2_CreativePoint;
    private javax.swing.JTextField jTextField3_AnalystPoint;
    private javax.swing.JTextField jTextField4_FinisherPoint;
    // End of variables declaration//GEN-END:variables
}
