
package flow2_team;

/**
 * Flow 2 - "Team"
 * Udarbejdet af:
 * Andreas og Laura
 * Torsdag 10.10.2013
 */

import java.awt.Panel;
import javax.swing.DefaultListModel;
import javax.swing.JPanel;
import javax.swing.text.NavigationFilter;

public class GUI extends javax.swing.JFrame
{
    Control c = new Control();
    
    //Herunder ses to attributter, kaldet "model1" og "model2":
    DefaultListModel personerUdenforTeams;
    DefaultListModel team1Listen;
    DefaultListModel team2Listen;
    DefaultListModel team3Listen;
    DefaultListModel team4Listen;
    
    //Herunder ses konstruktøren "GUI":
    public GUI()
    {
        initComponents();
        
        //Herunder instantieres DefaultListModel, og de to jLists sættes til at parre informationer med de to Model's.
        personerUdenforTeams = new DefaultListModel();
        team1Listen = new DefaultListModel();
        team2Listen = new DefaultListModel();
        team3Listen = new DefaultListModel();
        team4Listen = new DefaultListModel();
        
        jList2_AllePersonerUdenforTeams.setModel(personerUdenforTeams);
        jList2_TeamNo1.setModel(team1Listen);
        jList2_TeamNo2.setModel(team2Listen);
        jList2_TeamNo3.setModel(team3Listen);
        jList2_TeamNo4.setModel(team4Listen);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1_Forside = new javax.swing.JPanel();
        jButton1_OpretTeam = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1_OpretPerson = new javax.swing.JButton();
        jComboBox1_Teams = new javax.swing.JComboBox();
        jComboBox1_Personer = new javax.swing.JComboBox();
        jPanel2_OpretPerson = new javax.swing.JPanel();
        jLabel2_Navn = new javax.swing.JLabel();
        jLabel3_Alder = new javax.swing.JLabel();
        jLabel4_Køn = new javax.swing.JLabel();
        jComboBox1_Alder = new javax.swing.JComboBox();
        jTextField1_Fornavn = new javax.swing.JTextField();
        jTextField2_Efternavn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1_AdministratorPoint = new javax.swing.JTextField();
        jTextField2_CreativePoint = new javax.swing.JTextField();
        jTextField3_AnalystPoint = new javax.swing.JTextField();
        jTextField4_FinisherPoint = new javax.swing.JTextField();
        jButton1_OK_OpretPerson = new javax.swing.JButton();
        jButton1_GåTilForsiden_FraOpretPerson = new javax.swing.JButton();
        jRadioButton1_Mand = new javax.swing.JRadioButton();
        jRadioButton2_Kvinde = new javax.swing.JRadioButton();
        jPanel3_AllePersoner = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1_GåTilForsiden_FraAllePersoner = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8_Navn = new javax.swing.JLabel();
        jLabel9_Alder = new javax.swing.JLabel();
        jLabel10_Køn = new javax.swing.JLabel();
        jLabel11_Team = new javax.swing.JLabel();
        jLabel8_Navnet = new javax.swing.JLabel();
        jLabel9_Alderen = new javax.swing.JLabel();
        jLabel10_Kønnet = new javax.swing.JLabel();
        jLabel11_Teamet = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13_AdministratorPoint = new javax.swing.JLabel();
        jLabel14_AnalystPoint = new javax.swing.JLabel();
        jLabel15_CreativePoint = new javax.swing.JLabel();
        jLabel16_FinisherPoint = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton1_SletPerson = new javax.swing.JButton();
        jPanel4_OpretTeam = new javax.swing.JPanel();
        jButton3_GåTilForsiden_FraOpretTeam = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jList2_AllePersonerUdenforTeams = new javax.swing.JList();
        jButton1_Tilføj = new javax.swing.JButton();
        jButton2_Fjern = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1__TeamNo1 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jList2_TeamNo1 = new javax.swing.JList();
        jPanel2_TeamNo2 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jList2_TeamNo2 = new javax.swing.JList();
        jPanel3_TeamNo3 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jList2_TeamNo3 = new javax.swing.JList();
        jPanel4_TeamNo4 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jList2_TeamNo4 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jPanel5_AlleTeams = new javax.swing.JPanel();
        jButton1_Team1 = new javax.swing.JButton();
        jButton2_Team2 = new javax.swing.JButton();
        jButton3_Team3 = new javax.swing.JButton();
        jButton4_Team4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2_Team1 = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3_Team2 = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList4_Team3 = new javax.swing.JList();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList5_Team4 = new javax.swing.JList();
        jButton5_GåTilForsiden_FraAlleTeams = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1_OpretTeam.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        jButton1_OpretTeam.setText("OPRET TEAM");
        jButton1_OpretTeam.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1_OpretTeamActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 30)); // NOI18N
        jLabel1.setText("TEAM APPLIKATION");

        jButton1_OpretPerson.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        jButton1_OpretPerson.setText("OPRET PERSON");
        jButton1_OpretPerson.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1_OpretPersonActionPerformed(evt);
            }
        });

        jComboBox1_Teams.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alle Teams", "Team1", "Team2", "Team3", "Team4" }));
        jComboBox1_Teams.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                jComboBox1_TeamsItemStateChanged(evt);
            }
        });
        jComboBox1_Teams.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jComboBox1_TeamsActionPerformed(evt);
            }
        });

        jComboBox1_Personer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alle Personer", "Personer i Teams", "Personer uden for Teams" }));
        jComboBox1_Personer.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jComboBox1_PersonerActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1_ForsideLayout = new org.jdesktop.layout.GroupLayout(jPanel1_Forside);
        jPanel1_Forside.setLayout(jPanel1_ForsideLayout);
        jPanel1_ForsideLayout.setHorizontalGroup(
            jPanel1_ForsideLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1_ForsideLayout.createSequentialGroup()
                .add(jPanel1_ForsideLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1_ForsideLayout.createSequentialGroup()
                        .add(85, 85, 85)
                        .add(jButton1_OpretTeam, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 164, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1_ForsideLayout.createSequentialGroup()
                        .add(59, 59, 59)
                        .add(jComboBox1_Teams, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 214, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 122, Short.MAX_VALUE)
                .add(jPanel1_ForsideLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1_ForsideLayout.createSequentialGroup()
                        .add(jButton1_OpretPerson, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 161, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(84, 84, 84))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1_ForsideLayout.createSequentialGroup()
                        .add(jComboBox1_Personer, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 221, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(49, 49, 49))))
            .add(jPanel1_ForsideLayout.createSequentialGroup()
                .add(180, 180, 180)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 296, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1_ForsideLayout.setVerticalGroup(
            jPanel1_ForsideLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1_ForsideLayout.createSequentialGroup()
                .add(18, 18, 18)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 47, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jPanel1_ForsideLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton1_OpretPerson, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton1_OpretTeam, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 66, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1_ForsideLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jComboBox1_Personer, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jComboBox1_Teams, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(200, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("FORSIDE", jPanel1_Forside);

        jLabel2_Navn.setText("Navn:");

        jLabel3_Alder.setText("Alder:");

        jLabel4_Køn.setText("Køn:");

        jComboBox1_Alder.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alder", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40" }));

        jTextField1_Fornavn.setText("Fornavn(e)");

        jTextField2_Efternavn.setText("Efternavn");

        jLabel2.setText("Fordel 30 point mellem de 4 forskellige roller:");

        jLabel3.setText("ADMINISTRATOR");

        jLabel4.setText("ANALYST");

        jLabel5.setText("CREATIVE");

        jLabel6.setText("FINISHER");

        jTextField1_AdministratorPoint.setText("0-30");

        jTextField2_CreativePoint.setText("0-30");

        jTextField3_AnalystPoint.setText("0-30");

        jTextField4_FinisherPoint.setText("0-30");

        jButton1_OK_OpretPerson.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        jButton1_OK_OpretPerson.setText("OK");

        jButton1_GåTilForsiden_FraOpretPerson.setText("Gå til Forsiden");
        jButton1_GåTilForsiden_FraOpretPerson.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1_GåTilForsiden_FraOpretPersonActionPerformed(evt);
            }
        });

        jRadioButton1_Mand.setText("Mand");

        jRadioButton2_Kvinde.setText("Kvinde");

        org.jdesktop.layout.GroupLayout jPanel2_OpretPersonLayout = new org.jdesktop.layout.GroupLayout(jPanel2_OpretPerson);
        jPanel2_OpretPerson.setLayout(jPanel2_OpretPersonLayout);
        jPanel2_OpretPersonLayout.setHorizontalGroup(
            jPanel2_OpretPersonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2_OpretPersonLayout.createSequentialGroup()
                .addContainerGap()
                .add(jButton1_GåTilForsiden_FraOpretPerson, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 143, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jButton1_OK_OpretPerson)
                .add(36, 36, 36))
            .add(jPanel2_OpretPersonLayout.createSequentialGroup()
                .add(21, 21, 21)
                .add(jPanel2_OpretPersonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2_OpretPersonLayout.createSequentialGroup()
                        .add(jPanel2_OpretPersonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jLabel2_Navn, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jLabel3_Alder, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel2_OpretPersonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel2_OpretPersonLayout.createSequentialGroup()
                                .add(jTextField1_Fornavn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 168, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jTextField2_Efternavn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 197, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jComboBox1_Alder, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 110, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 309, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel2_OpretPersonLayout.createSequentialGroup()
                        .add(jLabel4_Køn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 61, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jRadioButton1_Mand, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jRadioButton2_Kvinde, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 82, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel2_OpretPersonLayout.createSequentialGroup()
                        .add(jPanel2_OpretPersonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 112, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPanel2_OpretPersonLayout.createSequentialGroup()
                                .add(25, 25, 25)
                                .add(jTextField1_AdministratorPoint, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(jPanel2_OpretPersonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel2_OpretPersonLayout.createSequentialGroup()
                                .add(18, 18, 18)
                                .add(jTextField3_AnalystPoint, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel2_OpretPersonLayout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 64, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(jPanel2_OpretPersonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel2_OpretPersonLayout.createSequentialGroup()
                                .add(18, 18, 18)
                                .add(jTextField2_CreativePoint, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel2_OpretPersonLayout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 66, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(jPanel2_OpretPersonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel2_OpretPersonLayout.createSequentialGroup()
                                .add(18, 18, 18)
                                .add(jTextField4_FinisherPoint, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel2_OpretPersonLayout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 66, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(197, Short.MAX_VALUE))
        );
        jPanel2_OpretPersonLayout.setVerticalGroup(
            jPanel2_OpretPersonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2_OpretPersonLayout.createSequentialGroup()
                .add(34, 34, 34)
                .add(jPanel2_OpretPersonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jTextField2_Efternavn)
                    .add(jLabel2_Navn, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jTextField1_Fornavn))
                .add(18, 18, 18)
                .add(jPanel2_OpretPersonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jLabel3_Alder, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jComboBox1_Alder))
                .add(18, 18, 18)
                .add(jPanel2_OpretPersonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel2_OpretPersonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel4_Køn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jRadioButton1_Mand))
                    .add(jRadioButton2_Kvinde, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .add(18, 18, 18)
                .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel2_OpretPersonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2_OpretPersonLayout.createSequentialGroup()
                        .add(jPanel2_OpretPersonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jPanel2_OpretPersonLayout.createSequentialGroup()
                                .add(jPanel2_OpretPersonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(jLabel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                            .add(jPanel2_OpretPersonLayout.createSequentialGroup()
                                .add(jLabel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(6, 6, 6)))
                        .add(jPanel2_OpretPersonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jTextField3_AnalystPoint, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jTextField1_AdministratorPoint, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jTextField2_CreativePoint, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jTextField4_FinisherPoint, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(jPanel2_OpretPersonLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel2_OpretPersonLayout.createSequentialGroup()
                                .add(18, 18, 18)
                                .add(jButton1_OK_OpretPerson)
                                .addContainerGap(89, Short.MAX_VALUE))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2_OpretPersonLayout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(jButton1_GåTilForsiden_FraOpretPerson)
                                .addContainerGap())))
                    .add(jPanel2_OpretPersonLayout.createSequentialGroup()
                        .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jTabbedPane1.addTab("Opret Person", jPanel2_OpretPerson);

        jList1.setModel(new javax.swing.AbstractListModel()
        {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jButton1_GåTilForsiden_FraAllePersoner.setText("Gå til Forsiden");
        jButton1_GåTilForsiden_FraAllePersoner.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1_GåTilForsiden_FraAllePersonerActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        jLabel7.setText("PERSON INFO");

        jLabel8_Navn.setText("NAVN: ");

        jLabel9_Alder.setText("ALDER: ");

        jLabel10_Køn.setText("KØN: ");

        jLabel11_Team.setText("TEAM: ");

        jLabel8_Navnet.setText("Fornavn(e) og Efternavn");

        jLabel9_Alderen.setText("Alder");

        jLabel10_Kønnet.setText("Mand eller Kvinde");

        jLabel11_Teamet.setText("Teamets Navn");

        jLabel8.setText("POINT-FORDELING:");

        jLabel9.setText("Administrator: ");

        jLabel10.setText("Analyst: ");

        jLabel11.setText("Creative: ");

        jLabel12.setText("Finisher: ");

        jLabel13_AdministratorPoint.setText("0-30");

        jLabel14_AnalystPoint.setText("0-30");

        jLabel15_CreativePoint.setText("0-30");

        jLabel16_FinisherPoint.setText("0-30");

        jLabel17.setText("point");

        jLabel18.setText("point");

        jLabel19.setText("point");

        jLabel20.setText("point");

        jButton1_SletPerson.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        jButton1_SletPerson.setText("SLET PERSON");

        org.jdesktop.layout.GroupLayout jPanel3_AllePersonerLayout = new org.jdesktop.layout.GroupLayout(jPanel3_AllePersoner);
        jPanel3_AllePersoner.setLayout(jPanel3_AllePersonerLayout);
        jPanel3_AllePersonerLayout.setHorizontalGroup(
            jPanel3_AllePersonerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3_AllePersonerLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3_AllePersonerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 318, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton1_GåTilForsiden_FraAllePersoner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 143, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(jPanel3_AllePersonerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3_AllePersonerLayout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(jPanel3_AllePersonerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel3_AllePersonerLayout.createSequentialGroup()
                                .add(0, 84, Short.MAX_VALUE)
                                .add(jLabel7)
                                .add(104, 104, 104))
                            .add(jPanel3_AllePersonerLayout.createSequentialGroup()
                                .add(jPanel3_AllePersonerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jPanel3_AllePersonerLayout.createSequentialGroup()
                                        .add(jPanel3_AllePersonerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jPanel3_AllePersonerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                                .add(jLabel9_Alder, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .add(jLabel8_Navn, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .add(jLabel10_Køn)
                                            .add(jLabel11_Team))
                                        .add(18, 18, 18)
                                        .add(jPanel3_AllePersonerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                            .add(jLabel8_Navnet, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                                            .add(jLabel9_Alderen, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .add(jLabel10_Kønnet, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .add(jLabel11_Teamet, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .add(jLabel8)
                                    .add(jPanel3_AllePersonerLayout.createSequentialGroup()
                                        .add(jPanel3_AllePersonerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jLabel9)
                                            .add(jLabel10)
                                            .add(jLabel11)
                                            .add(jLabel12))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jPanel3_AllePersonerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                            .add(jLabel13_AdministratorPoint, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                            .add(jLabel14_AnalystPoint, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .add(jLabel15_CreativePoint, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .add(jLabel16_FinisherPoint, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jPanel3_AllePersonerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                            .add(jLabel17, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                            .add(jLabel18, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .add(jLabel19, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .add(jLabel20, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addContainerGap(26, Short.MAX_VALUE))))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3_AllePersonerLayout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jButton1_SletPerson, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 151, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel3_AllePersonerLayout.setVerticalGroup(
            jPanel3_AllePersonerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3_AllePersonerLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3_AllePersonerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3_AllePersonerLayout.createSequentialGroup()
                        .add(jLabel7)
                        .add(10, 10, 10)
                        .add(jPanel3_AllePersonerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel8_Navn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel8_Navnet))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel3_AllePersonerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel9_Alder, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel9_Alderen))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel3_AllePersonerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel10_Køn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel10_Kønnet))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel3_AllePersonerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel11_Team, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel11_Teamet))
                        .add(18, 18, 18)
                        .add(jLabel8)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel3_AllePersonerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel9)
                            .add(jLabel13_AdministratorPoint)
                            .add(jLabel17))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel3_AllePersonerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel10)
                            .add(jLabel14_AnalystPoint)
                            .add(jLabel18))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel3_AllePersonerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel11)
                            .add(jLabel15_CreativePoint)
                            .add(jLabel19))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel3_AllePersonerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel12)
                            .add(jLabel16_FinisherPoint)
                            .add(jLabel20))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 21, Short.MAX_VALUE)
                        .add(jButton1_SletPerson))
                    .add(jScrollPane1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton1_GåTilForsiden_FraAllePersoner)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Alle Personer", jPanel3_AllePersoner);

        jButton3_GåTilForsiden_FraOpretTeam.setText("Gå til Forsiden");
        jButton3_GåTilForsiden_FraOpretTeam.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton3_GåTilForsiden_FraOpretTeamActionPerformed(evt);
            }
        });

        jList2_AllePersonerUdenforTeams.setModel(new javax.swing.AbstractListModel()
        {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(jList2_AllePersonerUdenforTeams);

        jButton1_Tilføj.setText("Tilføj >>");
        jButton1_Tilføj.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1_TilføjActionPerformed(evt);
            }
        });

        jButton2_Fjern.setText("<< Fjern");
        jButton2_Fjern.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2_FjernActionPerformed(evt);
            }
        });

        jScrollPane8.setViewportView(jList2_TeamNo1);

        org.jdesktop.layout.GroupLayout jPanel1__TeamNo1Layout = new org.jdesktop.layout.GroupLayout(jPanel1__TeamNo1);
        jPanel1__TeamNo1.setLayout(jPanel1__TeamNo1Layout);
        jPanel1__TeamNo1Layout.setHorizontalGroup(
            jPanel1__TeamNo1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1__TeamNo1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1__TeamNo1Layout.setVerticalGroup(
            jPanel1__TeamNo1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1__TeamNo1Layout.createSequentialGroup()
                .add(jScrollPane8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Team1", jPanel1__TeamNo1);

        jList2_TeamNo2.setModel(new javax.swing.AbstractListModel()
        {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane7.setViewportView(jList2_TeamNo2);

        org.jdesktop.layout.GroupLayout jPanel2_TeamNo2Layout = new org.jdesktop.layout.GroupLayout(jPanel2_TeamNo2);
        jPanel2_TeamNo2.setLayout(jPanel2_TeamNo2Layout);
        jPanel2_TeamNo2Layout.setHorizontalGroup(
            jPanel2_TeamNo2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2_TeamNo2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2_TeamNo2Layout.setVerticalGroup(
            jPanel2_TeamNo2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2_TeamNo2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Team2", jPanel2_TeamNo2);

        jScrollPane9.setViewportView(jList2_TeamNo3);

        org.jdesktop.layout.GroupLayout jPanel3_TeamNo3Layout = new org.jdesktop.layout.GroupLayout(jPanel3_TeamNo3);
        jPanel3_TeamNo3.setLayout(jPanel3_TeamNo3Layout);
        jPanel3_TeamNo3Layout.setHorizontalGroup(
            jPanel3_TeamNo3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3_TeamNo3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane9, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3_TeamNo3Layout.setVerticalGroup(
            jPanel3_TeamNo3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3_TeamNo3Layout.createSequentialGroup()
                .add(jScrollPane9, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Team3", jPanel3_TeamNo3);

        jScrollPane10.setViewportView(jList2_TeamNo4);

        org.jdesktop.layout.GroupLayout jPanel4_TeamNo4Layout = new org.jdesktop.layout.GroupLayout(jPanel4_TeamNo4);
        jPanel4_TeamNo4.setLayout(jPanel4_TeamNo4Layout);
        jPanel4_TeamNo4Layout.setHorizontalGroup(
            jPanel4_TeamNo4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4_TeamNo4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane10, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4_TeamNo4Layout.setVerticalGroup(
            jPanel4_TeamNo4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4_TeamNo4Layout.createSequentialGroup()
                .add(jScrollPane10, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Team4", jPanel4_TeamNo4);

        jButton1.setText("HENT ALLE PERSONER");

        org.jdesktop.layout.GroupLayout jPanel4_OpretTeamLayout = new org.jdesktop.layout.GroupLayout(jPanel4_OpretTeam);
        jPanel4_OpretTeam.setLayout(jPanel4_OpretTeamLayout);
        jPanel4_OpretTeamLayout.setHorizontalGroup(
            jPanel4_OpretTeamLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4_OpretTeamLayout.createSequentialGroup()
                .add(jPanel4_OpretTeamLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel4_OpretTeamLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(jButton3_GåTilForsiden_FraOpretTeam, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 143, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel4_OpretTeamLayout.createSequentialGroup()
                        .add(jPanel4_OpretTeamLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel4_OpretTeamLayout.createSequentialGroup()
                                .add(21, 21, 21)
                                .add(jScrollPane6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 209, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jPanel4_OpretTeamLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jButton1_Tilføj)
                                    .add(jButton2_Fjern)))
                            .add(jPanel4_OpretTeamLayout.createSequentialGroup()
                                .add(30, 30, 30)
                                .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 191, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jTabbedPane2)))
                .addContainerGap())
        );
        jPanel4_OpretTeamLayout.setVerticalGroup(
            jPanel4_OpretTeamLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4_OpretTeamLayout.createSequentialGroup()
                .add(jPanel4_OpretTeamLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel4_OpretTeamLayout.createSequentialGroup()
                        .add(114, 114, 114)
                        .add(jButton1_Tilføj)
                        .add(18, 18, 18)
                        .add(jButton2_Fjern)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jButton3_GåTilForsiden_FraOpretTeam))
                    .add(jPanel4_OpretTeamLayout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(jPanel4_OpretTeamLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jTabbedPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 334, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPanel4_OpretTeamLayout.createSequentialGroup()
                                .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jScrollPane6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 282, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(0, 30, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Opret Team", jPanel4_OpretTeam);

        jButton1_Team1.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 36)); // NOI18N
        jButton1_Team1.setText("TEAM 1");

        jButton2_Team2.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 36)); // NOI18N
        jButton2_Team2.setText("TEAM 2");

        jButton3_Team3.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 36)); // NOI18N
        jButton3_Team3.setText("TEAM 3");

        jButton4_Team4.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 36)); // NOI18N
        jButton4_Team4.setText("TEAM 4");

        jList2_Team1.setModel(new javax.swing.AbstractListModel()
        {
            String[] strings = { "Administrator: ", "Analyst: ", "Creative: ", "Finisher: " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2_Team1);

        jList3_Team2.setModel(new javax.swing.AbstractListModel()
        {
            String[] strings = { "Administrator: ", "Analyst: ", "Creative: ", "Finisher: " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList3_Team2);

        jList4_Team3.setModel(new javax.swing.AbstractListModel()
        {
            String[] strings = { "Administrator: ", "Analyst: ", "Creative: ", "Finisher: " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList4_Team3);

        jList5_Team4.setModel(new javax.swing.AbstractListModel()
        {
            String[] strings = { "Administrator: ", "Analyst: ", "Creative: ", "Finisher: " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(jList5_Team4);

        jButton5_GåTilForsiden_FraAlleTeams.setText("Gå til Forsiden");
        jButton5_GåTilForsiden_FraAlleTeams.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton5_GåTilForsiden_FraAlleTeamsActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel5_AlleTeamsLayout = new org.jdesktop.layout.GroupLayout(jPanel5_AlleTeams);
        jPanel5_AlleTeams.setLayout(jPanel5_AlleTeamsLayout);
        jPanel5_AlleTeamsLayout.setHorizontalGroup(
            jPanel5_AlleTeamsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5_AlleTeamsLayout.createSequentialGroup()
                .add(34, 34, 34)
                .add(jPanel5_AlleTeamsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel5_AlleTeamsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                        .add(jScrollPane4))
                    .add(jButton1_Team1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 162, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton3_Team3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 162, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(49, 49, 49)
                .add(jPanel5_AlleTeamsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel5_AlleTeamsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(jScrollPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                        .add(jScrollPane5))
                    .add(jButton2_Team2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 162, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton4_Team4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 162, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
            .add(jPanel5_AlleTeamsLayout.createSequentialGroup()
                .addContainerGap()
                .add(jButton5_GåTilForsiden_FraAlleTeams, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 143, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );
        jPanel5_AlleTeamsLayout.setVerticalGroup(
            jPanel5_AlleTeamsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5_AlleTeamsLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel5_AlleTeamsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jButton1_Team1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton2_Team2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel5_AlleTeamsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jScrollPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel5_AlleTeamsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jButton3_Team3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton4_Team4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel5_AlleTeamsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                    .add(jScrollPane4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .add(18, 18, 18)
                .add(jButton5_GåTilForsiden_FraAlleTeams)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Alle Teams", jPanel5_AlleTeams);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_OpretTeamActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1_OpretTeamActionPerformed
    {//GEN-HEADEREND:event_jButton1_OpretTeamActionPerformed
        //Når der trykkes på "Opret Team"-knappen, skal vi skifte til panelet "Opret Team".
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_jButton1_OpretTeamActionPerformed

    private void jComboBox1_TeamsItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_jComboBox1_TeamsItemStateChanged
    {//GEN-HEADEREND:event_jComboBox1_TeamsItemStateChanged
        
    }//GEN-LAST:event_jComboBox1_TeamsItemStateChanged

    private void jComboBox1_TeamsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jComboBox1_TeamsActionPerformed
    {//GEN-HEADEREND:event_jComboBox1_TeamsActionPerformed
        /**
        jComboBox1_Teams.setSelectedIndex(1);
        jComboBox1_Teams.addActionListener(); //Inde i () skal der stå den fane, som team 1 er på...
        
        jComboBox1_Teams.setSelectedIndex(2);
        jComboBox1_Teams.addActionListener(); //Inde i () skal der stå den fane, som team 2 er på...
        
        jComboBox1_Teams.setSelectedIndex(3);
        jComboBox1_Teams.addActionListener(); //Inde i () skal der stå den fane, som team 3 er på...
        
        jComboBox1_Teams.setSelectedIndex(4);
        jComboBox1_Teams.addActionListener(); //Inde i () skal der stå den fane, som team 4 er på...
        */
    }//GEN-LAST:event_jComboBox1_TeamsActionPerformed

    private void jButton1_GåTilForsiden_FraOpretPersonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1_GåTilForsiden_FraOpretPersonActionPerformed
    {//GEN-HEADEREND:event_jButton1_GåTilForsiden_FraOpretPersonActionPerformed
        //Når der trykkes på "Gå til Forsiden", skal vi skifte til Panel 1 (Forsiden).
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1_GåTilForsiden_FraOpretPersonActionPerformed

    private void jButton1_OpretPersonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1_OpretPersonActionPerformed
    {//GEN-HEADEREND:event_jButton1_OpretPersonActionPerformed
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jButton1_OpretPersonActionPerformed

    private void jComboBox1_PersonerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jComboBox1_PersonerActionPerformed
    {//GEN-HEADEREND:event_jComboBox1_PersonerActionPerformed
        /**
        jComboBox1_Personer.setSelectedIndex(1);
        jComboBox1_Personer.addActionListener();
        */
    }//GEN-LAST:event_jComboBox1_PersonerActionPerformed

    private void jButton1_GåTilForsiden_FraAllePersonerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1_GåTilForsiden_FraAllePersonerActionPerformed
    {//GEN-HEADEREND:event_jButton1_GåTilForsiden_FraAllePersonerActionPerformed
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1_GåTilForsiden_FraAllePersonerActionPerformed

    private void jButton3_GåTilForsiden_FraOpretTeamActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3_GåTilForsiden_FraOpretTeamActionPerformed
    {//GEN-HEADEREND:event_jButton3_GåTilForsiden_FraOpretTeamActionPerformed
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton3_GåTilForsiden_FraOpretTeamActionPerformed

    private void jButton5_GåTilForsiden_FraAlleTeamsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton5_GåTilForsiden_FraAlleTeamsActionPerformed
    {//GEN-HEADEREND:event_jButton5_GåTilForsiden_FraAlleTeamsActionPerformed
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton5_GåTilForsiden_FraAlleTeamsActionPerformed

    private void jButton1_TilføjActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1_TilføjActionPerformed
    {//GEN-HEADEREND:event_jButton1_TilføjActionPerformed
        //Hvis der trykkes på "Tilføj", bliver en person flyttet fra liste 1 (Personer udenfor teams) til en valgt team-liste:
        while (jPanel1__TeamNo1.hasFocus())
        {  
            Object valgt1 = jList2_AllePersonerUdenforTeams.getSelectedValue();
            boolean fundet1 = personerUdenforTeams.removeElement(valgt1);
            if (fundet1)
                team1Listen.addElement(valgt1);
        }
        
        while (jPanel2_TeamNo2.hasFocus())
        {
            Object valgt2 = jList2_AllePersonerUdenforTeams.getSelectedValue();
            boolean fundet2 = personerUdenforTeams.removeElement(valgt2);
            if (fundet2)
                team2Listen.addElement(valgt2);
        }
        
        while (jPanel3_TeamNo3.hasFocus())
        {
            Object valgt3 = jList2_AllePersonerUdenforTeams.getSelectedValue();
            boolean fundet3 = personerUdenforTeams.removeElement(valgt3);
            if (fundet3)
                team3Listen.addElement(valgt3);
        }
        
        while (jPanel4_TeamNo4.hasFocus())
        {
            Object valgt4 = jList2_AllePersonerUdenforTeams.getSelectedValue();
            boolean fundet4 = personerUdenforTeams.removeElement(valgt4);
            if (fundet4)
                team4Listen.addElement(valgt4);
        }
    }//GEN-LAST:event_jButton1_TilføjActionPerformed

    private void jButton2_FjernActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2_FjernActionPerformed
    {//GEN-HEADEREND:event_jButton2_FjernActionPerformed
        //Hvis der trykkes på "Fjern", bliver en person flyttet fra liste 2 (Personer i teams) tilbage til liste 1 (Personer udenfor teams)
        Object valgt2 = jList3_OprettedeTeams.getSelectedValue();
        boolean fundet2 = model2.removeElement(valgt2);
        if (fundet2)
            model1.addElement(valgt2);
    }//GEN-LAST:event_jButton2_FjernActionPerformed

    //Herunder ses main-metoden:
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new GUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1_GåTilForsiden_FraAllePersoner;
    private javax.swing.JButton jButton1_GåTilForsiden_FraOpretPerson;
    private javax.swing.JButton jButton1_OK_OpretPerson;
    private javax.swing.JButton jButton1_OpretPerson;
    private javax.swing.JButton jButton1_OpretTeam;
    private javax.swing.JButton jButton1_SletPerson;
    private javax.swing.JButton jButton1_Team1;
    private javax.swing.JButton jButton1_Tilføj;
    private javax.swing.JButton jButton2_Fjern;
    private javax.swing.JButton jButton2_Team2;
    private javax.swing.JButton jButton3_GåTilForsiden_FraOpretTeam;
    private javax.swing.JButton jButton3_Team3;
    private javax.swing.JButton jButton4_Team4;
    private javax.swing.JButton jButton5_GåTilForsiden_FraAlleTeams;
    private javax.swing.JComboBox jComboBox1_Alder;
    private javax.swing.JComboBox jComboBox1_Personer;
    private javax.swing.JComboBox jComboBox1_Teams;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel10_Køn;
    private javax.swing.JLabel jLabel10_Kønnet;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel11_Team;
    private javax.swing.JLabel jLabel11_Teamet;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13_AdministratorPoint;
    private javax.swing.JLabel jLabel14_AnalystPoint;
    private javax.swing.JLabel jLabel15_CreativePoint;
    private javax.swing.JLabel jLabel16_FinisherPoint;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel2_Navn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel3_Alder;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel4_Køn;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel8_Navn;
    private javax.swing.JLabel jLabel8_Navnet;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel9_Alder;
    private javax.swing.JLabel jLabel9_Alderen;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2_AllePersonerUdenforTeams;
    private javax.swing.JList jList2_Team1;
    private javax.swing.JList jList2_TeamNo1;
    private javax.swing.JList jList2_TeamNo2;
    private javax.swing.JList jList2_TeamNo3;
    private javax.swing.JList jList2_TeamNo4;
    private javax.swing.JList jList3_Team2;
    private javax.swing.JList jList4_Team3;
    private javax.swing.JList jList5_Team4;
    private javax.swing.JPanel jPanel1_Forside;
    private javax.swing.JPanel jPanel1__TeamNo1;
    private javax.swing.JPanel jPanel2_OpretPerson;
    private javax.swing.JPanel jPanel2_TeamNo2;
    private javax.swing.JPanel jPanel3_AllePersoner;
    private javax.swing.JPanel jPanel3_TeamNo3;
    private javax.swing.JPanel jPanel4_OpretTeam;
    private javax.swing.JPanel jPanel4_TeamNo4;
    private javax.swing.JPanel jPanel5_AlleTeams;
    private javax.swing.JRadioButton jRadioButton1_Mand;
    private javax.swing.JRadioButton jRadioButton2_Kvinde;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField1_AdministratorPoint;
    private javax.swing.JTextField jTextField1_Fornavn;
    private javax.swing.JTextField jTextField2_CreativePoint;
    private javax.swing.JTextField jTextField2_Efternavn;
    private javax.swing.JTextField jTextField3_AnalystPoint;
    private javax.swing.JTextField jTextField4_FinisherPoint;
    // End of variables declaration//GEN-END:variables
}
